# Generated by Django 3.1.2 on 2020-11-13 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.CharField(max_length=20)),
                ('clientName', models.CharField(max_length=20)),
                ('clientType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNumber', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=20)),
                ('cellTechnology', models.CharField(max_length=20)),
                ('cellManufacturer', models.CharField(max_length=20)),
                ('numberOfCells', models.CharField(max_length=20)),
                ('cellsInSeries', models.CharField(max_length=20)),
                ('seriesStrings', models.CharField(max_length=20)),
                ('numberOfDiodes', models.CharField(max_length=20)),
                ('productLength', models.CharField(max_length=20)),
                ('productWidth', models.CharField(max_length=20)),
                ('productWeight', models.CharField(max_length=20)),
                ('superstateType', models.CharField(max_length=20)),
                ('superstateManufacturer', models.CharField(max_length=20)),
                ('substrateType', models.CharField(max_length=20)),
                ('substrateManufacturer', models.CharField(max_length=20)),
                ('frameType', models.CharField(max_length=20)),
                ('frameAdhesive', models.CharField(max_length=20)),
                ('encapsulateType', models.CharField(max_length=20)),
                ('encapsulantManufacturer', models.CharField(max_length=20)),
                ('junctionType', models.CharField(max_length=20)),
                ('junctionManufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='testSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenceID', models.CharField(max_length=20)),
                ('sequenceName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='testStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardID', models.CharField(max_length=20)),
                ('standardName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('publishedDate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='PLACEHOLDER', max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('jobTitle', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('officePhone', models.CharField(max_length=20)),
                ('cellPhone', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.CharField(max_length=20)),
                ('serviceName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('fiRequired', models.CharField(max_length=20)),
                ('fiFrequency', models.CharField(max_length=20)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard')),
            ],
        ),
        migrations.CreateModel(
            name='performanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxVoltage', models.CharField(max_length=20)),
                ('voc', models.CharField(max_length=20)),
                ('isc', models.CharField(max_length=20)),
                ('vmp', models.CharField(max_length=20)),
                ('imp', models.CharField(max_length=20)),
                ('pmp', models.CharField(max_length=20)),
                ('ff', models.CharField(max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testsequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('faxNumber', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certNumber', models.CharField(max_length=20)),
                ('ID', models.CharField(max_length=20)),
                ('reportNumber', models.CharField(max_length=20)),
                ('issueDate', models.CharField(max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
