# Generated by Django 3.1.2 on 2020-11-13 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clientID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
