# Generated by Django 3.1.2 on 2020-11-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201113_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=20),
        ),
    ]
