# Generated by Django 3.1.2 on 2020-11-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201113_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clientID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
    ]
