# Generated by Django 3.1.2 on 2020-11-13 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201113_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='sequence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.testsequence'),
        ),
        migrations.AlterField(
            model_name='service',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.teststandard'),
        ),
    ]
